name: PR Label Checks

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize, ready_for_review]
  merge_group:

# This concurrency group exists with cancel-in-progress: true so that only the latest run of the workflow is executed (as its all that should matter).
concurrency:
  group: pr-label-checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fail_if_label_found:
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        if: ${{ github.event_name == 'pull_request' && contains( github.event.pull_request.labels.*.name, 'do not merge') }}
        run: |
          echo "PR has 'do not merge' label, failing."
          exit 1
      
      - name: Merge queue - skip label check
        if: ${{ github.event_name == 'merge_group' }}
        run: |
          echo "Merge queue: Label already validated in PR, skipping check"
          exit 0
